platform:ios, '7.0'
target 'BaoCai' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'AFNetworking'
    pod 'JSONKit-NoWarning'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Toast'
    pod 'libqrencode'
    pod 'MWPhotoBrowser'
    pod 'JSONModel'
    pod 'SDCycleScrollView'
    pod 'MarqueeLabel'
    pod 'KMNavigationBarTransition'
    pod 'TTTAttributedLabel'
    pod 'HyphenateLite_CN'
    pod 'CustomIOSAlertView'
    pod 'SSZipArchive'
    pod 'NJKWebViewProgress'
    pod 'PSTCollectionView'
    pod 'Masonry'
    
    pod 'UMengAnalytics'
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/Sina'
    pod 'UMengUShare/Social/WeChat'
    pod 'UMengUShare/Social/QQ'
    pod 'UMengUShare/Social/SMS'
    
    pod 'JPFPSStatus'

    source 'https://git.oschina.net/rarexray/LLPaySDKSpecs.git'
    pod 'LLPaySDK', '~>2.4.8'
end

target 'BaoCaiTests' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'AFNetworking'
    pod 'JSONKit-NoWarning'
end
